// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFriends(arg1) {
  return window['go']['main']['App']['GetFriends'](arg1);
}

export function GetSession() {
  return window['go']['main']['App']['GetSession']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ServerOnline() {
  return window['go']['main']['App']['ServerOnline']();
}

export function SignIn() {
  return window['go']['main']['App']['SignIn']();
}
