// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUsername(arg1, arg2) {
  return window['go']['main']['App']['CreateUsername'](arg1, arg2);
}

export function ForceAddRespModel() {
  return window['go']['main']['App']['ForceAddRespModel']();
}

export function GetFriends(arg1) {
  return window['go']['main']['App']['GetFriends'](arg1);
}

export function GetSession() {
  return window['go']['main']['App']['GetSession']();
}

export function ServerOnline() {
  return window['go']['main']['App']['ServerOnline']();
}

export function SignIn() {
  return window['go']['main']['App']['SignIn']();
}

export function ValidateUsername(arg1, arg2) {
  return window['go']['main']['App']['ValidateUsername'](arg1, arg2);
}
