// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {googleuser} from '../models';
import {apiresps} from '../models';

export function GetFriends(arg1:googleuser.GoogleUser):Promise<apiresps.Friends>;

export function GetSession():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ServerOnline():Promise<boolean>;

export function SignIn():Promise<googleuser.GoogleUser>;
