// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {user} from '../models';
import {apiresps} from '../models';

export function CreateUsername(arg1:user.User,arg2:string):Promise<apiresps.SetupUser>;

export function ForceAddRespModel():Promise<apiresps.JunkResp>;

export function GetFriends(arg1:user.User):Promise<apiresps.Friends>;

export function GetSession():Promise<string>;

export function ServerOnline():Promise<boolean>;

export function SignIn():Promise<apiresps.AwaitSignIn>;

export function ValidateUsername(arg1:user.User,arg2:string):Promise<apiresps.ValidateUsername>;
